---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.55.2
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: test
    image: golang:1.21
    commands:
      - go test -coverprofile cover.out -v ./...
      - go tool cover -func cover.out
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: build
    image: ghcr.io/codestation/drone-kaniko
    settings:
      repo: registry.megpoid.dev/codestation/go-s3-backup
      tags: latest
      registry: registry.megpoid.dev
      cache_from:
        - registry.megpoid.dev/codestation/go-s3-backup:${DRONE_BRANCH}-cache
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    environment:
      GOPROXY:
        from_secret: goproxy_url

trigger:
  branch:
    - master
