---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.43.0
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...

  - name: test
    image: golang:1.17
    commands:
      - go test -coverprofile cover.out -v ./...
      - go tool cover -func cover.out
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: build
    image: ghcr.io/codestation/drone-docker
    settings:
      repos:
        - registry.megpoid.xyz/codestation/go-s3-backup
        - codestation/go-s3-backup
      tags: latest
      registry: registry.megpoid.xyz
      buildkit: true
      platforms:
        - linux/arm64
        - linux/amd64
      cache:
        - registry.megpoid.xyz/codestation/go-s3-backup:${DRONE_BRANCH}-cache
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
        - CI_COMMIT_BRANCH=${DRONE_BRANCH}
        - CI_COMMIT_SHA=${DRONE_COMMIT_SHA}
        - CI_PIPELINE_CREATED_AT=${DRONE_BUILD_CREATED}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    environment:
      GOPROXY:
        from_secret: goproxy_url
    when:
      branch:
        - master

  - name: build-branch
    image: ghcr.io/codestation/drone-docker
    settings:
      repo: registry.megpoid.xyz/codestation/go-s3-backup
      tags: ${DRONE_BRANCH}
      registry: registry.megpoid.xyz
      buildkit: true
      platforms:
        - linux/arm64
      cache:
        - registry.megpoid.xyz/codestation/go-s3-backup:${DRONE_BRANCH}-cache
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
        - CI_COMMIT_BRANCH=${DRONE_BRANCH}
        - CI_COMMIT_SHA=${DRONE_COMMIT_SHA}
        - CI_PIPELINE_CREATED_AT=${DRONE_BUILD_CREATED}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    environment:
      GOPROXY:
        from_secret: goproxy_url
    when:
      branch:
        - testing

trigger:
  branch:
    - testing
