steps:
  lint:
    image: golangci/golangci-lint:v2.1.6
    commands:
      - golangci-lint run -v --timeout 10m ./...
    environment:
      GOPROXY:
        from_secret: goproxy_url

  test:
    image: golang:1.24
    commands:
      - go test -coverprofile cover.out -v ./...
      - go tool cover -func cover.out
    environment:
      GOPROXY:
        from_secret: goproxy_url

  build:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      registry: registry.megpoid.dev
      repo: registry.megpoid.dev/codestation/go-s3-backup
      tags:
        - latest
        - '${CI_COMMIT_BRANCH}'
        - '${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:10}'
      config:
        from_secret: registry_credentials

when:
  event:
    - push
    - manual
  branch:
    - master
